# Generated by Django 5.2.4 on 2025-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Hardware', 'Hardware'), ('Service', 'Service')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
